name: flicker_mail
description: "Flicker Mail"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.9+11
isar_version: &isar_version 3.1.0+1 # define the version to be used

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  email_validator: ^2.1.16
  flex_color_scheme: ^7.3.1
  flutter_dotenv: ^5.1.0
  go_router: ^14.1.4
  intl: ^0.19.0
  in_app_review: ^2.0.9
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  lottie: ^3.1.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.1
  sentry_flutter: ^8.5.0
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  qr_flutter: ^4.1.0
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: any
  flutter_gen_runner:

flutter_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21


#Flutter gen for assets config
flutter_gen:
  output: lib/const_gen/ # Optional (default: lib/gen/)
  line_length: 120

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - .env


