name: flicker_mail
description: "Flicker Mail"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
isar_version: &isar_version 3.1.0+1 # define the version to be used

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flex_color_scheme: ^7.3.1
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.1
  intl: ^0.18.1
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any
  flutter_launcher_icons: "^0.13.1"



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - .env

